### ISSUE TITLE
Quickstart throws Error

### ISSUE THREAD

**Issue by michas2** [isomorphic-git/isomorphic-git#1318] opened 2021-02-18 20:09 UTC
On the official quickstart page the cloning process on the second run button does not work for me.

On the page:
https://isomorphic-git.org/docs/en/quickstart

When I press the second button I get this:
```
i {name: "NotFoundError", message: "Could not find master.", stack: "NotFoundError: Could not find master.
    at Function.resolveAgainstMap (https://isomorphic-git.org/js/isomorphic-git/index.umd.min.js:1:9625)
    at https://isomorphic-git.org/js/isomorphic-git/index.umd.min.js:8:96271
    at Generator.next (<anonymous>)
    at x (https://isomorphic-git.org/js/isomorphic-git/index.umd.min.js:8:94662)
    at a (https://isomorphic-git.org/js/isomorphic-git/index.umd.min.js:8:94865)", fileName: undefined, lineNumber: undefined…}
name: "NotFoundError"
message: "Could not find master."
stack: "NotFoundError: Could not find master.
    at Function.resolveAgainstMap (https://isomorphic-git.org/js/isomorphic-git/index.umd.min.js:1:9625)
    at https://isomorphic-git.org/js/isomorphic-git/index.umd.min.js:8:96271
    at Generator.next (<anonymous>)
    at x (https://isomorphic-git.org/js/isomorphic-git/index.umd.min.js:8:94662)
    at a (https://isomorphic-git.org/js/isomorphic-git/index.umd.min.js:8:94865)"
fileName: undefined
lineNumber: undefined
columnNumber: undefined
```

Is this a bug in the code or is something wrong with my browser?

**Comment by alex-titarenko** [comment] 2021-02-18 20:18
The `master` branch was renamed to `main`.  The website should be updated.
You can actually change the sample to use `main` branch and it will work

**Comment by jcubic** [comment] 2021-06-22 21:27
Duplicate of #1298

**Closed by jcubic** 2021-06-22 21:27 UTC
Labels: documentation
