### ISSUE TITLE
Issue with adding a directory

### ISSUE THREAD

**Issue by sahas-** [isomorphic-git/isomorphic-git#1700] opened 2022-12-17 23:33 UTC
I'm using the browser, next.js app,isomorphic-git v1.21.0, webpack.

Below is the view of local repo from the browser (indexed-db). Creating a test_549 directory and .gitkeep file with some dummy content. However, when I commit and push it to remote, the directory structure is lost. The .gitkeep file is at the root. Below is the code snippet as well. Am I doing something wrong?

<img width="594" alt="Screen Shot 2022-12-17 at 5 08 28 PM" src="https://user-images.githubusercontent.com/10361685/208269761-7672309e-bdfa-4567-8ab2-87b849ebc385.png">

<img width="764" alt="Screen Shot 2022-12-17 at 5 32 09 PM" src="https://user-images.githubusercontent.com/10361685/208269781-3d2f9030-be08-434a-8edc-a4c4a21a1dbf.png">

**Comment by jcubic** [comment] 2022-12-18 00:05
Can you provide reproduction? If you can't share the code write a simple application that reproduces the problem. I don't think this has anything to do with Webpack or Next.js.

Please create a working code that we can test.

**Comment by sahas-** [comment] 2022-12-18 02:39
Please clone this repo https://gitlab.com/sahaswaranamam/iso-git-test.
Its a next.js app. Go to pages --> index.js, update lines 17-20.

`npm install`
`npm run dev`

Launch localhost:3000, click the Button on the screen and see the console.log output. You can also see the repo inside the indexed-db in local.

**Comment by jcubic** [comment] 2022-12-22 22:22
You really messed up the code, it took me few hours to fix all the bugs. Here is working code. I should church for this type of work:

```javascript
async function executeTest() {
  const repo_name = '/test'
  const remote_url = 'https://github.com/jcubic/git-test.git'
  const password = '<ACCESS TOKEN>'
  const name = '<username>'
  const email = '<email>'
  let fs = new FS('/local_repo');
  window.fs = fs;
  await git.clone({
    fs,
    http,
    dir: repo_name,
    ref: 'master',
    remote: 'origin',
    corsProxy: 'https://jcubic.pl/proxy.php?',
    url: remote_url,
    singleBranch: true,
    onAuth: () => ({ username: email, password: password }),
    onProgress: (message) => { console.log("progress", message) },
    onMessage: (message) => { console.log("message", message) },
    onAuthFailure: (err) => { console.log("auth failure", err) },
  })
      
  await git.setConfig({
    fs,
    dir: repo_name,
    path: 'user.name',
    value: email,
    path: 'remote.origin.url',
    value: remote_url
  });
      
    let dirName = "test_" + Math.round(Math.random() * 9999)
    await fs.promises.mkdir(`${repo_name}/${dirName}`);
    await fs.promises.writeFile(`${repo_name}/${dirName}/.gitkeep`, `creating a dummy file with ${Math.random()}`)
    await git.add({ fs, dir: repo_name, filepath: `${dirName}/.gitkeep` })
  console.log('added the file')
  let commit_payload = {
      fs,
      dir: repo_name,
      ref: 'master',
      author: {
        name,
        email
      },
      message: `adding .gitkeep at ${new Date()}`
    }
    await git.commit(commit_payload)
    console.log('committed the file')
    await git.push({
      fs,
      http,
      dir: repo_name,
      remote: 'origin',
      corsProxy: 'https://jcubic.pl/proxy.php?',
      url: remote_url,
      ref: 'master',
      onAuth: () => ({ username: name, password }),
      onProgress: (message) => { console.log("progress", message) },
      onMessage: (message) => { console.log("message", message) },
      onAuthFailure: (err) => { console.log("auth failure", err) },
    })
    console.log('pushed to remote')
}
```

**Comment by jcubic** [comment] 2022-12-22 22:23
I closing this since this is a bug in user's code and not even one bug.

**Closed by jcubic** 2022-12-22 22:23 UTC
