### ISSUE TITLE
Invalid checksum in GitIndex buffer: expected  but saw da39a3ee5e6b4b0d3255bfef95601890afd80709

### ISSUE THREAD

**Issue by belinidaniel** [isomorphic-git/isomorphic-git#1774] opened 2023-06-15 10:16 UTC
An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected  but saw da39a3ee5e6b4b0d3255bfef95601890afd80709

**Comment by jcubic** [comment] 2023-06-15 10:39
Can you share some details about the error? What software you use, and where this happens?

this looks like duplicate of https://github.com/isomorphic-git/isomorphic-git/issues/1733

**Comment by belinidaniel** [comment] 2023-06-15 12:19
Hello @jcubic I'm trying deploy with salesforce sfdx using the default config of SFDX with VScode

**Comment by mojavelinux** [comment] 2023-06-15 19:05
@jcubic I think the comment in the error message that instructs the user to report the issue to the isomorphic-git project should be removed. I've never found those sorts of suggestions to be productive.

**Comment by jcubic** [comment] 2023-06-15 21:01
Agree. The error was supposed to find errors in a library, but this is really annoying because people report here instead of the project they are using.

**Comment by jayree** [comment] 2023-06-15 23:12
@jcubic this issue is related to #1768 I've had the same index issue with one of my sfdx plugins using `statusmatrix`. Had to pin iso-git version to 1.23 to fix it.

**Comment by jcubic** [comment] 2023-06-16 09:14
I'll try to add a dummy PR with a proper bugfix commit message.

**Comment by dead-end** [comment] 2023-06-17 07:54
The issue at foresales: [https://github.com/forcedotcom/cli/issues/2194](https://github.com/forcedotcom/cli/issues/2194)

**Comment by AzferPervaiz** [comment] 2023-08-17 12:22
Had the same issue, it was fixed when I deleted the index file after searching for it, the file is mentioned as: .git/index

**Comment by jcubic** [comment] 2023-08-18 11:44
Try reporting this to project [forcedotcom/cli](https://github.com/forcedotcom/cli/issues).

I know that the error says to report it here, but the bug is in the Salesforce extension, nothing we can do about the bug in that project.

**Closed by jcubic** 2023-08-18 11:44 UTC
