### ISSUE TITLE
Clone fails when using isomorphic-git + isomorphic-git/lightning-fs with Angular 16

### ISSUE THREAD

**Issue by rraab-dev** [isomorphic-git/isomorphic-git#1782] opened 2023-06-23 08:14 UTC
Hello,

I'm currently trying to migrate an Angular 14 application to Angular 16. isomophic-git is used in combination with isomorphic-git/lightning-fs. When updated to Angular 16 I encountered the following error when trying to clone a repository:

![grafik](https://github.com/isomorphic-git/isomorphic-git/assets/53948988/ccbdb18f-fa0a-4ebb-a037-3f122c7b43a2)

I also created a new Angular 16 project and added only these two dependencies and tried to clone the public https://github.com/isomorphic-git/isomorphic-git repository with the same result to showcase the error:

Repository:
https://github.com/rraab-dev/angular-16-isomorphic-git

Import and clone:
https://github.com/rraab-dev/angular-16-isomorphic-git/blob/master/src/app/app.component.ts

Please be sure to mention:
- whether you are using Node or the Browser:
Browser (Chrome), Node version: 18.16.1, @angular/cli version 16.1.0, ng serve
- how you are using it (if you are using a bundler what bundler; if you are using a `<script>` tag what CDN URL)
Dependency in package.json. (From npmjs.com)

Any input on what I'm doing wrong / I could try?

Best regards and thanks for the great work / project.

**Comment by jcubic** [comment] 2023-06-23 09:28
Did you update isomorphic-git version or it state the same?

**Comment by rraab-dev** [comment] 2023-06-23 10:25
isomorphic-git/lightning-fs stayed the same (4.6.0) and isomorphic-git was updated from 1.19.0 to the latest version 1.24.2.

But I just tested it with both versions and I'm getting the same error on Angular 16 even when I do not change the version of isomorphic-git.

**Comment by dead-end** [comment] 2023-06-23 11:13
Hi, I did not work much with isomorphic-git in the browser, but I saw, that you use:
```
const fs = new FS('testClone');
```
As far as I understand it, this uses the default backend, which seams to be `CacheFS`, which is empty after a reload. I just tried:
```
const fs = new LightningFS('fs')
```
and this uses the indexdb.

**Comment by rraab-dev** [comment] 2023-06-23 12:15
I'm using lightning-fs as described here:
https://github.com/isomorphic-git/lightning-fs/tree/main#usage

This is also using an IndexedDB. At least an IndexedDB is being created in the browser after running the code:
![grafik](https://github.com/isomorphic-git/isomorphic-git/assets/53948988/3588a78d-3c1b-45db-8d26-142ae0888b86)

How are you importing LightningFS?

**Comment by jcubic** [comment] 2023-06-23 12:44
It's really hard to say what is wrong. isomorphic-git should have nothing to do with Angular. I don't see how they both can affect each other. Will run your app later and see to confrm.

**Comment by dead-end** [comment] 2023-06-23 12:57
I used lightning-fs as described in the quickstart:
https://isomorphic-git.org/docs/en/quickstart

![image](https://github.com/isomorphic-git/isomorphic-git/assets/30635084/ad400b86-8720-4151-8661-7bb0e1603721)

This is the code:

```html
  <script src="https://unpkg.com/@isomorphic-git/lightning-fs"></script>
  <script src="https://unpkg.com/isomorphic-git@beta"></script>
  <script type="module">

    import http from 'https://unpkg.com/isomorphic-git@beta/http/web/index.js'

    window.fs = new LightningFS('fs')
    window.pfs = window.fs.promises

    const dir = '/'

    await git.clone({
      fs,
      http,
      dir,
      corsProxy: 'https://cors.isomorphic-git.org',
      url: 'https://github.com/isomorphic-git/isomorphic-git',
      ref: 'main',
      singleBranch: true,
      depth: 10
    });

    alert('Done');
  </script>
```

**Comment by dead-end** [comment] 2023-06-23 13:27
Sorry, I just saw that `CacheFS` is only the cache of the defaul backend:
```
this._cache = new CacheFS(name);
```

**Comment by jcubic** [comment] 2023-06-23 16:52
Yes, CacheFS is just an implementation detail, the code uses IndexedDB. It uses [idb-keyval](https://github.com/isomorphic-git/idb-keyval), a fork of Jake Archibald's project.

**Comment by jcubic** [comment] 2023-06-23 17:38
So it seems that Angular monkey patch Promise object and breaks isomorphic git:

When I execute in console:

```
> Promise 
class ZoneAwarePromise {
    static toString() {
      return ZONE_AWARE_PROMISE_TO_STRING;
    }
    static resolve(value) {
      return resolvePromise(new this(null), RESOLVED, value);
    }
    static …
```

it throws a global error even if Promise is inside `try..catch`. So it means that Angular breaks a lot of JavaScript libraries out there. You can't use Promise anymore. You should report this to Angular which breaks the Web. This is Google so I'm not surprised that they give a shit about the JavaScript ecosystem.

To go forward you need to Debug ANgular source code and figure out the f*ck they did to Promise object with their ZONE (whatever it is).

**Comment by jcubic** [comment] 2023-06-23 18:16
You need to aks on Angular repo how to disable Zone on Promises. I was able to create a hack but it throw another errors like missing Buffer object:

```typescript
import { Component, OnInit } from '@angular/core';

import * as git from '../../../../isomorphic-git';
import http from 'isomorphic-git/http/web';

import FS from '@isomorphic-git/lightning-fs';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent implements OnInit {
  title = 'angular-16-isomorphic-git';

  async ngOnInit() {
    await this.testClone();
  }

  private async testClone() {
      await unpulute(async function() {
          // Reset lightning-fs filesystem / indexedDB
          if ((await indexedDB.databases())?.find((db) => db.name === 'testClone')) {
              indexedDB.deleteDatabase('testClone');
          }
          const fs = new FS('testClone');

          // Clone isomorphic-git repository from GitHub
          await git.clone({
              fs,
              http,
              dir: '/',
              corsProxy: 'https://cors.isomorphic-git.org',
              url: 'https://github.com/isomorphic-git/isomorphic-git',
              singleBranch: true,
              depth: 1,
              onMessage: (m) => console.log(m),
          });
      });
  }
}

declare global {
    interface Window {
        Promise: Promise<unknown> & PromiseConstructor;
    }
}

async function unpulute(thunk: () => Promise<void>) {
    const Promise = window.Promise;
    var iframe = document.createElement('iframe');
    document.body.appendChild(iframe);

    var iframeWindow = iframe.contentWindow;
    if (iframeWindow) {
        window.Promise = iframeWindow.Promise;
    }

    iframe.remove();
    await thunk();
    window.Promise = Promise;
}
```

I will not waste any more time on Angular.

**Comment by rraab-dev** [comment] 2023-06-24 08:37
@dead-end You're using in your example code the @beta version which had been last published 3 years ago (At least on npmjs.com): 
https://www.npmjs.com/package/isomorphic-git?activeTab=versions

Now I imported the git object in the script tag and saved it in the global window variable in index.html. And I'm using this git object then to perform the git actions. This is working fine with one catch: It only works till version 1.23.0 otherwise I'm getting the same error in the console again. (v 1.24.0)

So it seems to break with this version update:
https://github.com/isomorphic-git/isomorphic-git/compare/v1.23.0...v1.24.0

Strange is also if the dependency isomorphic-git is added in the package.json the error occurs with 1.23.0 and 1.24.0. (I added the exact version to package.json so "1.23.0" and "1.24.0".)

I added a commit on how I got it working at least with version 1.23.0:
https://github.com/rraab-dev/angular-16-isomorphic-git/commit/bab93e7a8d6449edd1261dac3e3434595910365c#diff-ce434ef5cc161194b450135a3586eb89357fc270e8aaa8e336db5a04e8d52fbe

Many thanks again and have a great weekend.

**Comment by mdreier-sap** [comment] 2023-07-14 11:22
I can confirm that any file system operation (in my case it is `git.setConfig(...)`) fails with `isomorphic-git` 1.24.3 together with `@isomorphic-git/lightning-fs` 4.6.0. There is pretty big change in commit ff2818f20ec336472aa094a2ee6714599a147359 to `src/models/FileSystem.js`, could be related to this issue.

**Comment by jcubic** [comment] 2023-07-14 13:56
Can you link to the commit I can't find this hash in the repository.

**Comment by jcubic** [comment] 2023-07-14 13:57
Can you link to the commit? I can't find it in the repository.

**Comment by mdreier-sap** [comment] 2023-07-14 13:59
I suspect it was merged via squash merge, here is the merged commit: https://github.com/isomorphic-git/isomorphic-git/commit/9b183f13a381a0134b83e4d211310fb1872ffff4

**Comment by jcubic** [comment] 2023-07-14 17:46
Do you have a reproduction of the issue? That PR adds a way to use a promises-based interface to FS instead of just a normal callback one. It should not affect in any way reading data from the filesystem.

**Comment by mdreier-sap** [comment] 2023-07-17 10:03
I got a reproducable example here: https://github.com/mdreier-sap/repro-isomorphic-git

As expected, the root cause is that the `window.Promise` object is replaced, in my case by SAPUI5's testing framework. If you remove the import in [`test.js`](https://github.com/mdreier-sap/repro-isomorphic-git/blob/04c8380ab2bd9f8ab69390a2cbedf8c61553caec/test.js#L1) it will start working again.

**Comment by jcubic** [comment] 2023-07-17 10:55
We can keep original Promise object somehow so no one overwrite it with wrong implementation but I don't know if that will not make those libraries stop working. I'm not sure if this will be possible at least with testing frameworks that always execute first. The same will happen with Angular compiler that will probably also run as first thing. Maybe add it as dependecy for this special case.

**Comment by mdreier-sap** [comment] 2023-07-17 10:57
I would think that the JavaScript way would be to check that the object has the expected methods (`then`, `catch`, ...) rather than checking against a concrete implementation/instance. But I'm not going to claim any expertise here.

**Comment by jcubic** [comment] 2023-07-17 17:59
I just checked this code and constructor.name of the promise was `v` because the code was minified by Webpack. Even if I run in develop mode. I've change the code to test if the object is Promise like since this is how JavaScript work, you can use promise like object with async/await they don't need to be real Promises.

```javascript
function isPromiseFs(fs) {
  const test = targetFs => {
    try {
      // If readFile returns a promise then we can probably assume the other
      // commands do as well
      return targetFs.readFile().catch(e => e)
    } catch (e) {
      return e
    }
  }
  return test(fs).constructor.name === 'Promise'
}
```

**Closed as completed** 2023-07-17 18:16 UTC
Labels: released
