### ISSUE TITLE
Running `git.add` on removed file throws an error

### ISSUE THREAD

**Issue by crutchcorn** [isomorphic-git/isomorphic-git#1099] opened 2020-04-02 21:15 UTC
I am using the React Native example and have noticed issues with trying to run `git.add` to a file that's been removed. Instead of adding it to the `staged` files that've been changed, I get a `NotFoundError`.

![image](https://user-images.githubusercontent.com/9100169/78300453-61cab580-74ec-11ea-92c2-9da364d85952.png)

**Comment by jcubic** [comment] 2020-04-02 21:21
You need to use git.remove, this what I'm doing to delete file:
```javascript
git.remove({fs, dir, filepath}).then(() => fs.unlink(path_name));
```
If I need to delete directory there is bit more code see my code:
https://github.com/jcubic/git/blob/master/js/main.js#L690

**Comment by jcubic** [comment] 2020-04-02 22:14
Sorry I'm not sure how to do that, you probably need to checkout single file, I'm not sure if that's possible. I only have gitReset but for whole repo and it wipe everything and run checkout on new branch.

**Comment by crutchcorn** [comment] 2020-06-24 01:37
@wmhilton I've noticed that there's a check to see if the file exists here:

https://github.com/isomorphic-git/isomorphic-git/blob/main/src/api/add.js#L62

And here:

https://github.com/isomorphic-git/isomorphic-git/blob/main/src/api/add.js#L73

I would be willing to remove those, but I know that there's an `oid = _writeObject`, and I'm not sure how the `_writeObject` would effectively work when the `object` is null. Would you be able to give me some guidance to help me figure out how to write this logic? Maybe some resources that I should read as a pre-req? I just don't know where to go from here

**Comment by crutchcorn** [comment] 2020-07-03 07:43
Wow `git add removedFileName` has some weird behaviors. Here's an example of a parsed git directory immediately after removing the file using `rm package.json`:

```
[
	{ "signature": "DIRC", "version": 2, "entries": 142 },
	// ...
	{
		"entry": 86,
		"ctime_seconds": 1593761850,
		"ctime_nanoseconds": 685003100,
		"mtime_seconds": 1593761850,
		"mtime_nanoseconds": 685003100,
		"dev": 42,
		"ino": 81191,
		"mode": 33188,
		"uid": 1000,
		"gid": 1000,
		"size": 1741,
		"sha1": "58c3e7cbffab58fcb4017993275b85795603479d",
		"flags": 12,
		"assume-valid": false,
		"extended": false,
		"stage": [false, false],
		"name": "package.json"
	},
	{
		"extension": 1,
		"signature": "TREE",
		"size": 875,
		"data": "DATA_HERE"
	},
	{ "checksum": true, "sha1": "bcfd94fa4717cc1976ff16c00f8d81c333e20082" }
]
```

> Both `index` files were indexed using [`gin`](https://github.com/sbp/gin) because using HEX editors from the 90s isn't fun

However, once `git add package.json` has been ran to add this change to the "stage" area, this "entry" disappears entirely.

**Comment by crutchcorn** [comment] 2020-07-03 08:41
Some notes for myself, as I continue to debug this:

- `git add package.json` totally removes it from the `index` file
- `git reset HEAD package.json` will unstage the deleted file without undeleting that file
     - When this is done, it is added _back_ to the `index` file
- There is a [`resetIndex` function in `isomorphic-git`](https://github.com/isomorphic-git/isomorphic-git/blob/main/src/api/resetIndex.js)
- There is a [`remove` function in `isomorphic-git`](https://github.com/isomorphic-git/isomorphic-git/blob/main/src/api/remove.js)

And, sure enough... When I run the relevant commands, they act the way I would """expect""" them to, now understanding the Git implementation a bit better:

```javascript
const git = require('isomorphic-git');
const fs = require('fs');
const http = require('isomorphic-git/http/web');
const fetch = require('node-fetch');
globalThis.fetch = fetch;

const path = require('path');
const currPath = path.resolve('./')


git.remove({fs, dir: currPath, filepath: 'package.json'}).then(() => console.log("DONE"))

// Once this is ran, it stages 'package.json'

git.resetIndex({fs, dir: currPath, filepath: 'package.json'}).then(() => console.log("DONE"))

// Once this is ran, it unstages 'package.json'
```

So I guess here's my question: Should this edgecase be handed by `isomorphic-git` or by the clients?

The commands are _techincally_ correct in their behavior, but the documentation for these commands infer that they would otherwise handle these edgecases:

> `remove` - Remove a file from the git index (aka staging area)

> `add` - Add a file to the git index (aka staging area)

As far as I see it, we should either update the documentation for these two commands and add a reference to this particular issue, or we should update the code for these commands and invisibly handle these edgecases. I'd be happy to make a PR to solve this problem and write tests confirming their behavior change if you'd like to go down the "handle edgecase" route. What do you think @wmhilton ?

**Comment by crutchcorn** [comment] 2020-07-14 23:33
@wmhilton I've fixed this issue in my app locally, and understand how to fix this via a PR. Should I submit it or are we going to expect users to solve for this via their clients?

**Comment by Nils-Kolvenbach** [comment] 2020-07-16 22:07
First of all, thank you very much for such an awesome library @wmhilton !

> You need to use git.remove, this what I'm doing to delete file:
> 
> ```js
> git.remove({fs, dir, filepath}).then(() => fs.unlink(path_name));
> ```
> 
> If I need to delete directory there is bit more code see here:
> https://github.com/jcubic/git/blob/master/js/main.js#L690

I don't think the issue is about removing it from the index, but rather adding the removal of the file to the staging area (to commit the deletion of it).

I've just ran into the same problem where my normal git workflow would be:
``` sh
touch test.txt
git add test.txt
git commit -m "Added test file"
rm test.txt
git add test.txt
git commit -m "Removed test file again"
```

With Isomorphic git it would look something like this:  
(Please correct me if I'm wrong)
``` node
await fs.promises.writeFile('test.txt', '');
await git.add({ fs, dir: '/', filepath: 'test.txt' });
await git.commit({...});
await fs.promises.unlink('test.txt');
await git.add({ fs, dir: '/', filepath: 'test.txt' });
await git.commit({...});
```

Where now I get an error like this:
`NotFoundError: Could not find test.txt.`
Most probably from [this line](https://github.com/isomorphic-git/isomorphic-git/blob/main/src/api/add.js#L62).

[Here is a Repl for it](https://repl.it/repls/LowestWeakMonitors).
If you comment out line 17, it works fine.

Since the documentation says the following about add:
> Add a file to the git index (aka staging area)

And the workflow via Git CLI also involves the add command, I would expect isomorphic-git to do the same.
Any thoughts on this? Am I thinking completely wrong?

**Comment by crutchcorn** [comment] 2020-07-17 04:25
@Nils-Kolvenbach you've convinced me that I should just open a PR instead of waiting for further discussion. It's clear from the documentation (and our confusion) that this is a bug, not a feature.

In the meantime, you can sidestep this issue by using:

```
git.remove
```

To stage a deleted file and:

```
git.resetIndex
```

To unstage a deleted file. I'm doing this for my app (https://github.com/crutchcorn/GitShark/) and it works perfectly.

I'll make a notice when the PR is made live

**Comment by jcubic** [comment] 2021-12-14 19:49
@crutchcorn You've added this more than year ago, did you solved the issue? It seems that you didn't added a PR. Do you want to contribute?

**Comment by jcubic** [comment] 2021-12-14 19:52
I think that it should work like this:

1. Check if file exists, if yes run the rest of the code
2. If file don't exists don't throw exception yet, but check if the file is in the index
3. If file is in the index run git.remove
4. If file is not in index throw an error

**Comment by jcubic** [comment] 2021-12-14 20:02
It seems that you can do this logic without any modification to the library:

```javascript
// git add to staging
const stat = await git.status({ fs, dir: '/gaiman', filepath: 'index.js' });

if (stat === '*deleted') { // file was removed from the tree and it's not staged
    git.remove({ fs, dir: '/gaiman', filepath: 'index.js' });
} else {
    git.add({ fs, dir: '/gaiman', filepath: 'index.js' });
}

// git unstage
git.resetIndex({ fs, dir: '/gaiman', filepath: 'index.js' });
```

So I will close this issue.

**Closed by jcubic** 2021-12-14 20:02 UTC

**Comment by linonetwo** [comment] 2022-04-04 08:42
How to commit all delete-file?

```
await add({ dir, filepath: '.', fs });
```

This seems not able to add all deletion. Running `git add .` in terminal actually add those chagnes.

**Comment by jcubic** [comment] 2022-04-04 10:48
@linonetwo please read my comment above.

**Comment by jcubic** [comment] 2022-04-04 10:51
@linonetwo `.` is the directory. You will need to use a glob pattern library if you want to remove all files. And not add but `git.delete`.

**Comment by jcubic** [comment] 2022-04-04 13:44
Sorry for my mistake everything is correct, the function is `git.remove()` that removes items from Git Index.

**Comment by jcubic** [comment] 2022-04-04 13:50
You can see how I've implemented git add in my Git Web Terminal: https://github.com/jcubic/git/blob/gh-pages/js/main.js#L884

The issue with my code is that it doesn't support `git add .` but it would be easy to add you only need to list all files like (the first branch in 889) but it should use the same code as in else that allow deleting all commands (here there is only delete a single file).
