### ISSUE TITLE
fetch does not create the desired ref, and does not report a missing ref

### ISSUE THREAD

**Issue by emmerich** [isomorphic-git/isomorphic-git#1305] opened 2021-01-26 16:31 UTC
This may be linked to #1299.

When we use `git.fetch` with a ref that doesn't exist, the fetch completes successfully but the ref isn't created.

```
await git.initialize({ dir, fs });
await git.fetch({ dir, fs, ref: 'my-ref' });

await git.resolveRef({ dir, fs, ref: 'my-ref' }); // NotFoundError
```

This is due to an empty catch clause in fetch: https://github.com/isomorphic-git/isomorphic-git/blob/main/src/commands/fetch.js#L200

Could we maybe make a change to make it easier to see what's going on? It took me a while to figure out that my ref wasn't being created as that's the way the doc makes it out. What about writing the ref as part of the fetch process?

Using isomorphic-git in Node.

Cheers again for your work on this project!

**Comment by jcubic** [comment] 2021-06-22 21:36
Hi, this is been a while but can you create a reproduction that works? There are no `initialize` function and you can't run fetch using the URL.

**Comment by jcubic** [comment] 2021-06-28 17:11
I've tried to reproduce the issue, and fetch throw error when it can't find ref.
Here is proper reproduction that works fine:
```javascript
const fs = require('fs');
const git = require('isomorphic-git');
const http = require('isomorphic-git/http/node');
const dir = './bar';

(async () => {
    try {
        const url = 'https://github.com/isomorphic-git/isomorphic-git';

        await git.init({ dir, fs });
        await git.addRemote({ fs, dir, remote: 'origin', url });

        await git.fetch({ dir, http, fs, ref: 'my-ref' });

        await git.resolveRef({ dir, fs, ref: 'my-ref' });
    } catch(e) {
        console.log(e.message);
    }
})();
```

I'm closing the issue since I cannot reproduce the error.

**Closed by jcubic** 2021-06-28 17:11 UTC

**Comment by jcubic** [comment] 2021-06-28 17:12
Unfortunately, there is no error if your code is broken and don't execute all required commands in order.
